server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: springboot-mastery-api
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
